<a href="https://colab.research.google.com/github/a-forty-two/zee_9_may_22/blob/main/TF_Pooling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
temp = [0., 0., 1., 0., 0., 2., 1., 0., 1., 0.]
values = tf.reshape(temp, [1,1,2,5])
# PRODUCT of shape should be constant!

In [3]:
print("TF version = " + tf.__version__)
values
# eager evaluation

TF version = 2.8.0


<tf.Tensor: shape=(1, 1, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 1., 0., 0.],
         [2., 1., 0., 1., 0.]]]], dtype=float32)>

In [1]:
%tensorflow_version 1.x
import tensorflow as tf
temp = [0., 0., 1., 0., 0., 2., 1., 0., 1., 0.]
values = tf.reshape(temp, [1,1,2,5])
print("TF version = " + tf.__version__)
values
# Lazy evaluation-> graph will be waited, and built later

TensorFlow 1.x selected.
TF version = 1.15.2


<tf.Tensor 'Reshape:0' shape=(1, 1, 2, 5) dtype=float32>

In [9]:
%tensorflow_version 2.x
import tensorflow as tf
temp = [0., 0., 1., 0., 0., 2., 1., 0., 1., 0., 1, 1]
values = tf.reshape(temp, [1,1,3,4])
values

<tf.Tensor: shape=(1, 1, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 1., 0.],
         [0., 2., 1., 0.],
         [1., 0., 1., 1.]]]], dtype=float32)>

In [ ]:
# 1,1,1,1 -> SCALAR
# 1,1,1,X -> Vector 
# 1,1,M,N -> Matrix 
# 1,L,M,N -> Cube/Cuboids


In [10]:
avgpool = tf.nn.pool(input=values, window_shape=(1,2), pooling_type='AVG', padding ='SAME')
maxpool=  tf.nn.pool(input=values, window_shape=(1,2), pooling_type='MAX', padding ='SAME')

In [11]:
avgpool

<tf.Tensor: shape=(1, 1, 3, 4), dtype=float32, numpy=
array([[[[0. , 1. , 1. , 0. ],
         [0.5, 1. , 1. , 0.5],
         [1. , 0. , 1. , 1. ]]]], dtype=float32)>

In [12]:
maxpool

<tf.Tensor: shape=(1, 1, 3, 4), dtype=float32, numpy=
array([[[[0., 2., 1., 0.],
         [1., 2., 1., 1.],
         [1., 0., 1., 1.]]]], dtype=float32)>

In [16]:
temp = [0., 0., 1., 0., 0., 2., 1., 0., 1., 0., 1, 1]
values = tf.reshape(temp, [1,2,3,2])
avgpool = tf.nn.pool(input=values, window_shape=(2,2), pooling_type='AVG', padding ='VALID')
maxpool=  tf.nn.pool(input=values, window_shape=(2,2), pooling_type='MAX', padding ='VALID')

In [18]:
values

<tf.Tensor: shape=(1, 2, 3, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [1., 0.],
         [0., 2.]],

        [[1., 0.],
         [1., 0.],
         [1., 1.]]]], dtype=float32)>

In [17]:
avgpool

<tf.Tensor: shape=(1, 1, 2, 2), dtype=float32, numpy=
array([[[[0.75, 0.  ],
         [0.75, 0.75]]]], dtype=float32)>

In [7]:
maxpool

<tf.Tensor: shape=(1, 0, 1, 5), dtype=float32, numpy=array([], shape=(1, 0, 1, 5), dtype=float32)>

In [19]:
tf.__version__

'2.8.0'

In [ ]:
#Matrix-> 3X2  * 9X9
# 1024 X 768
# 5X5 